#define private public
#define protected public
#include "python_util.h"
// This file has been generated by Py++.

#include "boost/python.hpp"

#include "boost/python/suite/indexing/vector_indexing_suite.hpp"

#include "boost/python/suite/indexing/map_indexing_suite.hpp"

#include "common_util.h"

#include "MLCore/Predictor.h"

#include "MLCore/TextPredictor.h"

#include "Identifer.h"
const int gezi::Identifer::NullId;

#include "MLCore/PredictorFactory.h"

#include "Numeric/Vector/Vector.h"

#include "Numeric/Vector/WeightVector.h"

#include "Numeric/Vector/vector_util.h"

#include "feature/FeatureVector.h"

#include "feature/features_util.h"

#include "feature/FeatureExtractor.h"

#include "feature/FeaturesExtractorMgr.h"

namespace bp = boost::python;

struct FeatureExtractor_wrapper : gezi::FeatureExtractor, bp::wrapper< gezi::FeatureExtractor > {

FeatureExtractor_wrapper(gezi::FeatureExtractor const & arg )
: gezi::FeatureExtractor( arg )
, bp::wrapper< gezi::FeatureExtractor >(){
// copy constructor

}

FeatureExtractor_wrapper(::std::string name="" )
: gezi::FeatureExtractor( name )
, bp::wrapper< gezi::FeatureExtractor >(){
// constructor

}

virtual void extract(  ) {
if( bp::override func_extract = this->get_override( "extract" ) )
func_extract(  );
else
this->gezi::FeatureExtractor::extract(  );
}


void default_extract(  ) {
gezi::FeatureExtractor::extract( );
}

virtual void init(  ) {
if( bp::override func_init = this->get_override( "init" ) )
func_init(  );
else
this->gezi::FeatureExtractor::init(  );
}


void default_init(  ) {
gezi::FeatureExtractor::init( );
}

virtual void process( ::gezi::Feature * feature ) {
if( bp::override func_process = this->get_override( "process" ) )
func_process( boost::python::ptr(feature) );
else
this->gezi::FeatureExtractor::process( boost::python::ptr(feature) );
}


void default_process( ::gezi::Feature * feature ) {
gezi::FeatureExtractor::process( boost::python::ptr(feature) );
}

};

struct Predictor_wrapper : gezi::Predictor, bp::wrapper< gezi::Predictor > {

Predictor_wrapper(gezi::Predictor const & arg )
: gezi::Predictor( arg )
, bp::wrapper< gezi::Predictor >(){
// copy constructor

}

Predictor_wrapper( )
: gezi::Predictor( )
, bp::wrapper< gezi::Predictor >(){
// null constructor

}

Predictor_wrapper(::gezi::NormalizerPtr normalizer, ::gezi::CalibratorPtr calibrator, ::gezi::FeatureNamesVector const & featureNames )
: gezi::Predictor( normalizer, calibrator, boost::ref(featureNames) )
, bp::wrapper< gezi::Predictor >(){
// constructor

}

Predictor_wrapper(::gezi::CalibratorPtr calibrator, ::gezi::FeatureNamesVector const & featureNames )
: gezi::Predictor( calibrator, boost::ref(featureNames) )
, bp::wrapper< gezi::Predictor >(){
// constructor

}

Predictor_wrapper(::gezi::FeatureNamesVector const & featureNames )
: gezi::Predictor( boost::ref(featureNames) )
, bp::wrapper< gezi::Predictor >(){
// constructor

}

virtual bool CustomLoad( ::std::string path ) {
if( bp::override func_CustomLoad = this->get_override( "CustomLoad" ) )
return func_CustomLoad( path );
else
return this->gezi::Predictor::CustomLoad( path );
}


bool default_CustomLoad( ::std::string path ) {
return gezi::Predictor::CustomLoad( path );
}

virtual bool CustomLoad_( ::std::string path ) {
if( bp::override func_CustomLoad_ = this->get_override( "CustomLoad_" ) )
return func_CustomLoad_( path );
else
return this->gezi::Predictor::CustomLoad_( path );
}


bool default_CustomLoad_( ::std::string path ) {
return gezi::Predictor::CustomLoad_( path );
}

virtual void CustomSave(  ) {
if( bp::override func_CustomSave = this->get_override( "CustomSave" ) )
func_CustomSave(  );
else
this->gezi::Predictor::CustomSave(  );
}


void default_CustomSave(  ) {
gezi::Predictor::CustomSave( );
}

virtual void CustomSave( ::std::string path ) {
if( bp::override func_CustomSave = this->get_override( "CustomSave" ) )
func_CustomSave( path );
else
this->gezi::Predictor::CustomSave( path );
}


void default_CustomSave( ::std::string path ) {
gezi::Predictor::CustomSave( path );
}

virtual void CustomSave_( ::std::string path ) {
if( bp::override func_CustomSave_ = this->get_override( "CustomSave_" ) )
func_CustomSave_( path );
else
this->gezi::Predictor::CustomSave_( path );
}


void default_CustomSave_( ::std::string path ) {
gezi::Predictor::CustomSave_( path );
}

virtual ::gezi::PredictionKind GetPredictionKind(  ) {
if( bp::override func_GetPredictionKind = this->get_override( "GetPredictionKind" ) )
return func_GetPredictionKind(  );
else
return this->gezi::Predictor::GetPredictionKind(  );
}


::gezi::PredictionKind default_GetPredictionKind(  ) {
return gezi::Predictor::GetPredictionKind( );
}

virtual bool Load( ::std::string path ) {
if( bp::override func_Load = this->get_override( "Load" ) )
return func_Load( path );
else
return this->gezi::Predictor::Load( path );
}


bool default_Load( ::std::string path ) {
return gezi::Predictor::Load( path );
}

virtual bool LoadBin( ::std::string path ) {
if( bp::override func_LoadBin = this->get_override( "LoadBin" ) )
return func_LoadBin( path );
else
return this->gezi::Predictor::LoadBin( path );
}


bool default_LoadBin( ::std::string path ) {
return gezi::Predictor::LoadBin( path );
}

virtual bool LoadText( ::std::string path ) {
if( bp::override func_LoadText = this->get_override( "LoadText" ) )
return func_LoadText( path );
else
return this->gezi::Predictor::LoadText( path );
}


bool default_LoadText( ::std::string path ) {
return gezi::Predictor::LoadText( path );
}

virtual bool LoadText_( ::std::string file ) {
if( bp::override func_LoadText_ = this->get_override( "LoadText_" ) )
return func_LoadText_( file );
else
return this->gezi::Predictor::LoadText_( file );
}


bool default_LoadText_( ::std::string file ) {
return gezi::Predictor::LoadText_( file );
}

virtual bool Load_( ::std::string file ) {
if( bp::override func_Load_ = this->get_override( "Load_" ) )
return func_Load_( file );
else
return this->gezi::Predictor::Load_( file );
}


bool default_Load_( ::std::string file ) {
return gezi::Predictor::Load_( file );
}

virtual ::Float Margin( ::gezi::Vector & features ){
if( bp::override func_Margin = this->get_override( "Margin" ) )
return func_Margin( boost::ref(features) );
else
return this->gezi::Predictor::Margin( boost::ref(features) );
}

virtual ::std::string Name(  ) {
if( bp::override func_Name = this->get_override( "Name" ) )
return func_Name(  );
else
return this->gezi::Predictor::Name(  );
}


::std::string default_Name(  ) {
return gezi::Predictor::Name( );
}

virtual ::Float Output( ::gezi::InstancePtr instance ) {
if( bp::override func_Output = this->get_override( "Output" ) )
return func_Output( instance );
else
return this->gezi::Predictor::Output( instance );
}


::Float default_Output( ::gezi::InstancePtr instance ) {
return gezi::Predictor::Output( instance );
}

virtual ::Float Output( ::std::string line ) {
if( bp::override func_Output = this->get_override( "Output" ) )
return func_Output( line );
else
return this->gezi::Predictor::Output( line );
}


::Float default_Output( ::std::string line ) {
return gezi::Predictor::Output( line );
}

virtual ::Float Predict( ::std::string line, ::Float & output ) {
if( bp::override func_Predict = this->get_override( "Predict" ) )
return func_Predict( line, output );
else
return this->gezi::Predictor::Predict( line, output );
}


::Float default_Predict( ::std::string line, ::Float & output ) {
return gezi::Predictor::Predict( line, output );
}

virtual ::Float Predict( ::gezi::InstancePtr instance ) {
if( bp::override func_Predict = this->get_override( "Predict" ) )
return func_Predict( instance );
else
return this->gezi::Predictor::Predict( instance );
}


::Float default_Predict( ::gezi::InstancePtr instance ) {
return gezi::Predictor::Predict( instance );
}

virtual ::Float Predict( ::gezi::Vector & features ) {
if( bp::override func_Predict = this->get_override( "Predict" ) )
return func_Predict( boost::ref(features) );
else
return this->gezi::Predictor::Predict( boost::ref(features) );
}


::Float default_Predict( ::gezi::Vector & features ) {
return gezi::Predictor::Predict( boost::ref(features) );
}

virtual ::Float Predict( ::gezi::InstancePtr instance, ::Float & output ) {
if( bp::override func_Predict = this->get_override( "Predict" ) )
return func_Predict( instance, output );
else
return this->gezi::Predictor::Predict( instance, output );
}


::Float default_Predict( ::gezi::InstancePtr instance, ::Float & output ) {
return gezi::Predictor::Predict( instance, output );
}

virtual void Save(  ) {
if( bp::override func_Save = this->get_override( "Save" ) )
func_Save(  );
else
this->gezi::Predictor::Save(  );
}


void default_Save(  ) {
gezi::Predictor::Save( );
}

virtual void Save( ::std::string path ) {
if( bp::override func_Save = this->get_override( "Save" ) )
func_Save( path );
else
this->gezi::Predictor::Save( path );
}


void default_Save( ::std::string path ) {
gezi::Predictor::Save( path );
}

virtual void SaveBin( ::std::string path ) {
if( bp::override func_SaveBin = this->get_override( "SaveBin" ) )
func_SaveBin( path );
else
this->gezi::Predictor::SaveBin( path );
}


void default_SaveBin( ::std::string path ) {
gezi::Predictor::SaveBin( path );
}

virtual void SaveCode( ::std::string codeTypeStr="cpp" ) {
if( bp::override func_SaveCode = this->get_override( "SaveCode" ) )
func_SaveCode( codeTypeStr );
else
this->gezi::Predictor::SaveCode( codeTypeStr );
}


void default_SaveCode( ::std::string codeTypeStr="cpp" ) {
gezi::Predictor::SaveCode( codeTypeStr );
}

virtual void SaveCode_( ::std::string file, ::gezi::CodeType codeType ) {
if( bp::override func_SaveCode_ = this->get_override( "SaveCode_" ) )
func_SaveCode_( file, codeType );
else
this->gezi::Predictor::SaveCode_( file, codeType );
}


void default_SaveCode_( ::std::string file, ::gezi::CodeType codeType ) {
gezi::Predictor::SaveCode_( file, codeType );
}

virtual void SaveFeaturesGain( int topNum=0 ) {
if( bp::override func_SaveFeaturesGain = this->get_override( "SaveFeaturesGain" ) )
func_SaveFeaturesGain( topNum );
else
this->gezi::Predictor::SaveFeaturesGain( topNum );
}


void default_SaveFeaturesGain( int topNum=0 ) {
gezi::Predictor::SaveFeaturesGain( topNum );
}

virtual void SaveJson( ::std::string file ) {
if( bp::override func_SaveJson = this->get_override( "SaveJson" ) )
func_SaveJson( file );
else
this->gezi::Predictor::SaveJson( file );
}


void default_SaveJson( ::std::string file ) {
gezi::Predictor::SaveJson( file );
}

virtual void SaveJson_( ::std::string file ) {
if( bp::override func_SaveJson_ = this->get_override( "SaveJson_" ) )
func_SaveJson_( file );
else
this->gezi::Predictor::SaveJson_( file );
}


void default_SaveJson_( ::std::string file ) {
gezi::Predictor::SaveJson_( file );
}

virtual void SaveText( ::std::string file ) {
if( bp::override func_SaveText = this->get_override( "SaveText" ) )
func_SaveText( file );
else
this->gezi::Predictor::SaveText( file );
}


void default_SaveText( ::std::string file ) {
gezi::Predictor::SaveText( file );
}

virtual void SaveText_( ::std::string file ) {
if( bp::override func_SaveText_ = this->get_override( "SaveText_" ) )
func_SaveText_( file );
else
this->gezi::Predictor::SaveText_( file );
}


void default_SaveText_( ::std::string file ) {
gezi::Predictor::SaveText_( file );
}

virtual void SaveXml( ::std::string file ) {
if( bp::override func_SaveXml = this->get_override( "SaveXml" ) )
func_SaveXml( file );
else
this->gezi::Predictor::SaveXml( file );
}


void default_SaveXml( ::std::string file ) {
gezi::Predictor::SaveXml( file );
}

virtual void SaveXml_( ::std::string file ) {
if( bp::override func_SaveXml_ = this->get_override( "SaveXml_" ) )
func_SaveXml_( file );
else
this->gezi::Predictor::SaveXml_( file );
}


void default_SaveXml_( ::std::string file ) {
gezi::Predictor::SaveXml_( file );
}

virtual void Save_( ::std::string file ) {
if( bp::override func_Save_ = this->get_override( "Save_" ) )
func_Save_( file );
else
this->gezi::Predictor::Save_( file );
}


void default_Save_( ::std::string file ) {
gezi::Predictor::Save_( file );
}

virtual ::std::string ToFeaturesGainSummary( int topNum=0 ) {
if( bp::override func_ToFeaturesGainSummary = this->get_override( "ToFeaturesGainSummary" ) )
return func_ToFeaturesGainSummary( topNum );
else
return this->gezi::Predictor::ToFeaturesGainSummary( topNum );
}


::std::string default_ToFeaturesGainSummary( int topNum=0 ) {
return gezi::Predictor::ToFeaturesGainSummary( topNum );
}

virtual ::std::string ToGainSummary( ::gezi::Vector & features ) {
if( bp::override func_ToGainSummary = this->get_override( "ToGainSummary" ) )
return func_ToGainSummary( boost::ref(features) );
else
return this->gezi::Predictor::ToGainSummary( boost::ref(features) );
}


::std::string default_ToGainSummary( ::gezi::Vector & features ) {
return gezi::Predictor::ToGainSummary( boost::ref(features) );
}

};

BOOST_PYTHON_MODULE(libmelt_predict_debug){
DEF_VEC(ivec);
DEF_VEC(dvec);
DEF_VEC(uvec);
DEF_VEC(svec);
DEF_VEC(ulvec);
DEF_MAP(id_map);
DEF_MAP(sd_map);
DEF_MAP(si_map);
DEF_MAP(ss_map);
DEF_PAIR(ii_pair);
DEF_PAIR(si_pair);
DEF_PAIR(wsi_pair);
DEF_VEC(si_pair_vec);
DEF_VEC(wsi_pair_vec);
DEF_SET(iset);
DEF_SET(lset);
DEF_SET(ulset);

{ //::std::vector< std::string >
typedef bp::class_< std::vector< std::string > > vector_less__std_scope_string__greater__exposer_t;
vector_less__std_scope_string__greater__exposer_t vector_less__std_scope_string__greater__exposer = vector_less__std_scope_string__greater__exposer_t( "vector_less__std_scope_string__greater_" );
bp::scope vector_less__std_scope_string__greater__scope( vector_less__std_scope_string__greater__exposer );
vector_less__std_scope_string__greater__exposer.def( bp::vector_indexing_suite< ::std::vector< std::string >, true >() )
VEC_METHOD(::std::vector< std::string >);
}

{ //::std::vector< std::string >
typedef bp::class_< std::vector< std::string > > vector_less__std_scope_string__greater__exposer_t;
vector_less__std_scope_string__greater__exposer_t vector_less__std_scope_string__greater__exposer = vector_less__std_scope_string__greater__exposer_t( "vector_less__std_scope_string__greater_" );
bp::scope vector_less__std_scope_string__greater__scope( vector_less__std_scope_string__greater__exposer );
vector_less__std_scope_string__greater__exposer.def( bp::vector_indexing_suite< ::std::vector< std::string >, true >() )
VEC_METHOD(::std::vector< std::string >);
}

{ //::std::vector< int >
typedef bp::class_< std::vector< int > > ivec_exposer_t;
ivec_exposer_t ivec_exposer = ivec_exposer_t( "ivec" );
bp::scope ivec_scope( ivec_exposer );
ivec_exposer.def( bp::vector_indexing_suite< ::std::vector< int >, true >() )
VEC_METHOD(::std::vector< int >);
}

{ //::std::vector< gezi::FeaturesExtractor* >
typedef bp::class_< std::vector< gezi::FeaturesExtractor* > > vector_less__gezi_scope_FeaturesExtractor_ptr___greater__exposer_t;
vector_less__gezi_scope_FeaturesExtractor_ptr___greater__exposer_t vector_less__gezi_scope_FeaturesExtractor_ptr___greater__exposer = vector_less__gezi_scope_FeaturesExtractor_ptr___greater__exposer_t( "vector_less__gezi_scope_FeaturesExtractor_ptr___greater_" );
bp::scope vector_less__gezi_scope_FeaturesExtractor_ptr___greater__scope( vector_less__gezi_scope_FeaturesExtractor_ptr___greater__exposer );
vector_less__gezi_scope_FeaturesExtractor_ptr___greater__exposer.def( bp::vector_indexing_suite< ::std::vector< gezi::FeaturesExtractor* > >() )
VEC_METHOD(::std::vector< gezi::FeaturesExtractor* >);
}

{ //::std::vector< gezi::FeatureVector::Feature >
typedef bp::class_< std::vector< gezi::FeatureVector::Feature > > vector_less__gezi_scope_FeatureVector_scope_Feature__greater__exposer_t;
vector_less__gezi_scope_FeatureVector_scope_Feature__greater__exposer_t vector_less__gezi_scope_FeatureVector_scope_Feature__greater__exposer = vector_less__gezi_scope_FeatureVector_scope_Feature__greater__exposer_t( "vector_less__gezi_scope_FeatureVector_scope_Feature__greater_" );
bp::scope vector_less__gezi_scope_FeatureVector_scope_Feature__greater__scope( vector_less__gezi_scope_FeatureVector_scope_Feature__greater__exposer );
vector_less__gezi_scope_FeatureVector_scope_Feature__greater__exposer.def( bp::vector_indexing_suite< ::std::vector< gezi::FeatureVector::Feature > >() )
VEC_METHOD(::std::vector< gezi::FeatureVector::Feature >);
}

{ //::std::vector< double >
typedef bp::class_< std::vector< double > > vector_less__double__greater__exposer_t;
vector_less__double__greater__exposer_t vector_less__double__greater__exposer = vector_less__double__greater__exposer_t( "vector_less__double__greater_" );
bp::scope vector_less__double__greater__scope( vector_less__double__greater__exposer );
vector_less__double__greater__exposer.def( bp::vector_indexing_suite< ::std::vector< double >, true >() )
VEC_METHOD(::std::vector< double >);
}

{ //::std::vector< double >
typedef bp::class_< std::vector< double >, boost::noncopyable > vector_less__double__greater__exposer_t;
vector_less__double__greater__exposer_t vector_less__double__greater__exposer = vector_less__double__greater__exposer_t( "vector_less__double__greater_" );
bp::scope vector_less__double__greater__scope( vector_less__double__greater__exposer );
vector_less__double__greater__exposer.def( bp::vector_indexing_suite< ::std::vector< double >, true >() )
VEC_METHOD(::std::vector< double >);
}

bp::class_< std::vector< std::shared_ptr<gezi::Predictor> > >("vector_less__boost_scope_shared_ptr_less_gezi_scope_Predictor_greater___greater_")
.def( bp::vector_indexing_suite< ::std::vector< std::shared_ptr<gezi::Predictor> >, true >() )
VEC_METHOD(::std::vector< std::shared_ptr<gezi::Predictor> >);

bp::class_< std::map< std::string, double > >("map_less__std_scope_string_comma__double__greater_")
.def( bp::map_indexing_suite< ::std::map< std::string, double >, true >() )
MAP_METHOD(::std::map< std::string COMMA  double >);

bp::class_< std::map< int, double > >("map_less__int_comma__double__greater_")
.def( bp::map_indexing_suite< ::std::map< int, double >, true >() )
MAP_METHOD(::std::map< int COMMA  double >);

bp::class_< std::map< int, double > >("map_less__int_comma__double__greater_")
.def( bp::map_indexing_suite< ::std::map< int, double >, true >() )
MAP_METHOD(::std::map< int COMMA  double >);

bp::enum_< gezi::CodeType>("CodeType")
.value("C", gezi::CodeType::C)
.value("Python", gezi::CodeType::Python)
.value("Php", gezi::CodeType::Php)
.export_values()
;

{ //::gezi::FeatureExtractor
typedef bp::class_< FeatureExtractor_wrapper > FeatureExtractor_exposer_t;
FeatureExtractor_exposer_t FeatureExtractor_exposer = FeatureExtractor_exposer_t( "FeatureExtractor", bp::init< bp::optional< std::string > >(( bp::arg("name")="" )) );
bp::scope FeatureExtractor_scope( FeatureExtractor_exposer );
bp::implicitly_convertible< std::string, gezi::FeatureExtractor >();
{ //::gezi::FeatureExtractor::add

typedef void ( ::gezi::FeatureExtractor::*add_function_type )( double,::std::string ) ;

FeatureExtractor_exposer.def(
"add"
, add_function_type( &::gezi::FeatureExtractor::add )
, ( bp::arg("value"), bp::arg("name")="" ) );

}
{ //::gezi::FeatureExtractor::add

typedef void ( ::gezi::FeatureExtractor::*add_function_type )( double *,int,::std::string ) ;

FeatureExtractor_exposer.def(
"add"
, add_function_type( &::gezi::FeatureExtractor::add )
, ( bp::arg("values"), bp::arg("n"), bp::arg("name")="" ) );

}
{ //::gezi::FeatureExtractor::bind

typedef void ( ::gezi::FeatureExtractor::*bind_function_type )( ::gezi::Feature * ) ;

FeatureExtractor_exposer.def(
"bind"
, bind_function_type( &::gezi::FeatureExtractor::bind )
, ( bp::arg("feature") ) );

}
{ //::gezi::FeatureExtractor::extract

typedef void ( ::gezi::FeatureExtractor::*extract_function_type )(  ) ;
typedef void ( FeatureExtractor_wrapper::*default_extract_function_type )(  ) ;

FeatureExtractor_exposer.def(
"extract"
, extract_function_type(&::gezi::FeatureExtractor::extract)
, default_extract_function_type(&FeatureExtractor_wrapper::default_extract) );

}
{ //::gezi::FeatureExtractor::feature

typedef ::gezi::Feature * ( ::gezi::FeatureExtractor::*feature_function_type )(  ) ;

FeatureExtractor_exposer.def(
"feature"
, feature_function_type( &::gezi::FeatureExtractor::feature )
, bp::return_internal_reference<>());

}
{ //::gezi::FeatureExtractor::init

typedef void ( ::gezi::FeatureExtractor::*init_function_type )(  ) ;
typedef void ( FeatureExtractor_wrapper::*default_init_function_type )(  ) ;

FeatureExtractor_exposer.def(
"init"
, init_function_type(&::gezi::FeatureExtractor::init)
, default_init_function_type(&FeatureExtractor_wrapper::default_init) );

}
{ //::gezi::FeatureExtractor::name

typedef ::std::string ( ::gezi::FeatureExtractor::*name_function_type )(  ) ;

FeatureExtractor_exposer.def(
"name"
, name_function_type( &::gezi::FeatureExtractor::name ) );

}
{ //::gezi::FeatureExtractor::process

typedef void ( ::gezi::FeatureExtractor::*process_function_type )( ::gezi::Feature * ) ;
typedef void ( FeatureExtractor_wrapper::*default_process_function_type )( ::gezi::Feature * ) ;

FeatureExtractor_exposer.def(
"process"
, process_function_type(&::gezi::FeatureExtractor::process)
, default_process_function_type(&FeatureExtractor_wrapper::default_process)
, ( bp::arg("feature") ) );

}
}

{ //::gezi::Vector
typedef bp::class_< gezi::Vector > Vector_exposer_t;
Vector_exposer_t Vector_exposer = Vector_exposer_t( "Vector", bp::init< >() );
bp::scope Vector_scope( Vector_exposer );
VEC_METHOD2(Vector_exposer, gezi::Vector);
Vector_exposer.def( bp::init< gezi::Vector const & >(( bp::arg("arg0") )) );
Vector_exposer.def( bp::init< int >(( bp::arg("length_") )) );
bp::implicitly_convertible< int, gezi::Vector >();
Vector_exposer.def( bp::init< Float, int >(( bp::arg("value_"), bp::arg("length_") )) );
Vector_exposer.def( bp::init< int, Float >(( bp::arg("length_"), bp::arg("value_") )) );
Vector_exposer.def( bp::init< std::map< int, double > const & >(( bp::arg("m") )) );
bp::implicitly_convertible< std::map< int, double > const &, gezi::Vector >();
Vector_exposer.def( bp::init< int, ivec &, std::vector< double > & >(( bp::arg("length_"), bp::arg("indices_"), bp::arg("values_") )) );
Vector_exposer.def( bp::init< ivec &, std::vector< double > &, bp::optional< int > >(( bp::arg("indices_"), bp::arg("values_"), bp::arg("length_")=(int)(1024000) )) );
Vector_exposer.def( bp::init< std::vector< double > & >(( bp::arg("values_") )) );
bp::implicitly_convertible< std::vector< double > &, gezi::Vector >();
Vector_exposer.def( bp::init< std::string, bp::optional< int, int, std::string > >(( bp::arg("input"), bp::arg("startIndex")=(int)(0), bp::arg("length_")=(int)(1024000), bp::arg("sep")=",\011 " )) );
Vector_exposer.def( bp::init< __gnu_cxx::__normal_iterator< double*, std::vector< double > >, __gnu_cxx::__normal_iterator< double*, std::vector< double > > >(( bp::arg("first"), bp::arg("end") )) );
{ //::gezi::Vector::Add

typedef void ( ::gezi::Vector::*Add_function_type )( ::Float ) ;

Vector_exposer.def(
"Add"
, Add_function_type( &::gezi::Vector::Add )
, ( bp::arg("value") ) );

}
{ //::gezi::Vector::Add

typedef void ( ::gezi::Vector::*Add_function_type )( int,::Float ) ;

Vector_exposer.def(
"Add"
, Add_function_type( &::gezi::Vector::Add )
, ( bp::arg("index"), bp::arg("value") ) );

}
{ //::gezi::Vector::Add

typedef void ( ::gezi::Vector::*Add_function_type )( ::gezi::Vector const & ) ;

Vector_exposer.def(
"Add"
, Add_function_type( &::gezi::Vector::Add )
, ( bp::arg("other") ) );

}
{ //::gezi::Vector::AddMap

typedef void ( ::gezi::Vector::*AddMap_function_type )( ::std::map< int, double > const & ) ;

Vector_exposer.def(
"AddMap"
, AddMap_function_type( &::gezi::Vector::AddMap )
, ( bp::arg("m") ) );

}
{ //::gezi::Vector::AllStr

typedef ::std::string ( ::gezi::Vector::*AllStr_function_type )( ::std::string ) const;

Vector_exposer.def(
"AllStr"
, AllStr_function_type( &::gezi::Vector::AllStr )
, ( bp::arg("sep")="," ) );

}
{ //::gezi::Vector::CheckInvariants

typedef void ( ::gezi::Vector::*CheckInvariants_function_type )(  ) ;

Vector_exposer.def(
"CheckInvariants"
, CheckInvariants_function_type( &::gezi::Vector::CheckInvariants ) );

}
{ //::gezi::Vector::Clear

typedef void ( ::gezi::Vector::*Clear_function_type )(  ) ;

Vector_exposer.def(
"Clear"
, Clear_function_type( &::gezi::Vector::Clear ) );

}
{ //::gezi::Vector::Count

typedef int ( ::gezi::Vector::*Count_function_type )(  ) const;

Vector_exposer.def(
"Count"
, Count_function_type( &::gezi::Vector::Count ) );

}
{ //::gezi::Vector::DenseStr

typedef ::std::string ( ::gezi::Vector::*DenseStr_function_type )( ::std::string ) const;

Vector_exposer.def(
"DenseStr"
, DenseStr_function_type( &::gezi::Vector::DenseStr )
, ( bp::arg("sep")="," ) );

}
{ //::gezi::Vector::Densify

typedef void ( ::gezi::Vector::*Densify_function_type )( ::Float ) ;

Vector_exposer.def(
"Densify"
, Densify_function_type( &::gezi::Vector::Densify )
, ( bp::arg("maxSparsity") ) );

}
{ //::gezi::Vector::Densify

typedef void ( ::gezi::Vector::*Densify_function_type )(  ) ;

Vector_exposer.def(
"Densify"
, Densify_function_type( &::gezi::Vector::Densify ) );

}
{ //::gezi::Vector::Empty

typedef bool ( ::gezi::Vector::*Empty_function_type )(  ) const;

Vector_exposer.def(
"Empty"
, Empty_function_type( &::gezi::Vector::Empty ) );

}
{ //::gezi::Vector::ForceDense

typedef void ( ::gezi::Vector::*ForceDense_function_type )(  ) ;

Vector_exposer.def(
"ForceDense"
, ForceDense_function_type( &::gezi::Vector::ForceDense ) );

}
{ //::gezi::Vector::ForceSparse

typedef void ( ::gezi::Vector::*ForceSparse_function_type )(  ) ;

Vector_exposer.def(
"ForceSparse"
, ForceSparse_function_type( &::gezi::Vector::ForceSparse ) );

}
{ //::gezi::Vector::Index

typedef int ( ::gezi::Vector::*Index_function_type )( int ) const;

Vector_exposer.def(
"Index"
, Index_function_type( &::gezi::Vector::Index )
, ( bp::arg("index") ) );

}
{ //::gezi::Vector::Indices

typedef ::ivec const & ( ::gezi::Vector::*Indices_function_type )(  ) const;

Vector_exposer.def(
"Indices"
, Indices_function_type( &::gezi::Vector::Indices )
, bp::return_value_policy< bp::copy_const_reference >() );

}
{ //::gezi::Vector::Indices

typedef ::ivec & ( ::gezi::Vector::*Indices_function_type )(  ) ;

Vector_exposer.def(
"Indices"
, Indices_function_type( &::gezi::Vector::Indices )
, bp::return_internal_reference<>());

}
{ //::gezi::Vector::Init

typedef void ( ::gezi::Vector::*Init_function_type )( ::std::string,int,int,::std::string ) ;

Vector_exposer.def(
"Init"
, Init_function_type( &::gezi::Vector::Init )
, ( bp::arg("input"), bp::arg("startIndex")=(int)(0), bp::arg("length_")=(int)(0), bp::arg("sep")=",\011 " ) );

}
{ //::gezi::Vector::Init

typedef void ( ::gezi::Vector::*Init_function_type )( int,::std::vector< int > &,::std::vector< double > & ) ;

Vector_exposer.def(
"Init"
, Init_function_type( &::gezi::Vector::Init )
, ( bp::arg("length_"), bp::arg("indices_"), bp::arg("values_") ) );

}
{ //::gezi::Vector::Init

typedef void ( ::gezi::Vector::*Init_function_type )( ::std::vector< double > & ) ;

Vector_exposer.def(
"Init"
, Init_function_type( &::gezi::Vector::Init )
, ( bp::arg("values_") ) );

}
{ //::gezi::Vector::IsDense

typedef bool ( ::gezi::Vector::*IsDense_function_type )(  ) const;

Vector_exposer.def(
"IsDense"
, IsDense_function_type( &::gezi::Vector::IsDense ) );

}
{ //::gezi::Vector::IsSparse

typedef bool ( ::gezi::Vector::*IsSparse_function_type )(  ) const;

Vector_exposer.def(
"IsSparse"
, IsSparse_function_type( &::gezi::Vector::IsSparse ) );

}
{ //::gezi::Vector::Length

typedef int ( ::gezi::Vector::*Length_function_type )(  ) const;

Vector_exposer.def(
"Length"
, Length_function_type( &::gezi::Vector::Length ) );

}
{ //::gezi::Vector::MakeDense

typedef void ( ::gezi::Vector::*MakeDense_function_type )(  ) ;

Vector_exposer.def(
"MakeDense"
, MakeDense_function_type( &::gezi::Vector::MakeDense ) );

}
{ //::gezi::Vector::MakeSparse

typedef void ( ::gezi::Vector::*MakeSparse_function_type )(  ) ;

Vector_exposer.def(
"MakeSparse"
, MakeSparse_function_type( &::gezi::Vector::MakeSparse ) );

}
{ //::gezi::Vector::Norm

typedef ::Float ( ::gezi::Vector::*Norm_function_type )(  ) const;

Vector_exposer.def(
"Norm"
, Norm_function_type( &::gezi::Vector::Norm ) );

}
{ //::gezi::Vector::NumNonZeros

typedef int ( ::gezi::Vector::*NumNonZeros_function_type )(  ) ;

Vector_exposer.def(
"NumNonZeros"
, NumNonZeros_function_type( &::gezi::Vector::NumNonZeros ) );

}
{ //::gezi::Vector::PrepareDense

typedef void ( ::gezi::Vector::*PrepareDense_function_type )(  ) ;

Vector_exposer.def(
"PrepareDense"
, PrepareDense_function_type( &::gezi::Vector::PrepareDense ) );

}
{ //::gezi::Vector::Resize

typedef void ( ::gezi::Vector::*Resize_function_type )( int,::Float ) ;

Vector_exposer.def(
"Resize"
, Resize_function_type( &::gezi::Vector::Resize )
, ( bp::arg("length_"), bp::arg("value_")=0 ) );

}
{ //::gezi::Vector::ScaleBy

typedef void ( ::gezi::Vector::*ScaleBy_function_type )( ::Float ) ;

Vector_exposer.def(
"ScaleBy"
, ScaleBy_function_type( &::gezi::Vector::ScaleBy )
, ( bp::arg("d") ) );

}
{ //::gezi::Vector::SetIndex

typedef void ( ::gezi::Vector::*SetIndex_function_type )( int,int ) ;

Vector_exposer.def(
"SetIndex"
, SetIndex_function_type( &::gezi::Vector::SetIndex )
, ( bp::arg("index"), bp::arg("indexValue") ) );

}
{ //::gezi::Vector::SetLength

typedef void ( ::gezi::Vector::*SetLength_function_type )( int ) ;

Vector_exposer.def(
"SetLength"
, SetLength_function_type( &::gezi::Vector::SetLength )
, ( bp::arg("length_") ) );

}
{ //::gezi::Vector::SetValue

typedef void ( ::gezi::Vector::*SetValue_function_type )( int,::Float ) ;

Vector_exposer.def(
"SetValue"
, SetValue_function_type( &::gezi::Vector::SetValue )
, ( bp::arg("index"), bp::arg("value") ) );

}
{ //::gezi::Vector::Sparsify

typedef void ( ::gezi::Vector::*Sparsify_function_type )( ::Float ) ;

Vector_exposer.def(
"Sparsify"
, Sparsify_function_type( &::gezi::Vector::Sparsify )
, ( bp::arg("maxSparsity") ) );

}
{ //::gezi::Vector::Sparsify

typedef void ( ::gezi::Vector::*Sparsify_function_type )(  ) ;

Vector_exposer.def(
"Sparsify"
, Sparsify_function_type( &::gezi::Vector::Sparsify ) );

}
{ //::gezi::Vector::SquaredNorm

typedef ::Float ( ::gezi::Vector::*SquaredNorm_function_type )(  ) const;

Vector_exposer.def(
"SquaredNorm"
, SquaredNorm_function_type( &::gezi::Vector::SquaredNorm ) );

}
{ //::gezi::Vector::Str

typedef ::std::string ( ::gezi::Vector::*Str_function_type )( ::std::string ) const;

Vector_exposer.def(
"Str"
, Str_function_type( &::gezi::Vector::Str )
, ( bp::arg("sep")="," ) );

}
{ //::gezi::Vector::Subtract

typedef void ( ::gezi::Vector::*Subtract_function_type )( ::gezi::Vector const & ) ;

Vector_exposer.def(
"Subtract"
, Subtract_function_type( &::gezi::Vector::Subtract )
, ( bp::arg("other") ) );

}
{ //::gezi::Vector::Swap

typedef void ( ::gezi::Vector::*Swap_function_type )( ::gezi::Vector & ) ;

Vector_exposer.def(
"Swap"
, Swap_function_type( &::gezi::Vector::Swap )
, ( bp::arg("other") ) );

}
{ //::gezi::Vector::ToDense

typedef void ( ::gezi::Vector::*ToDense_function_type )( ::std::vector< double > & ) ;

Vector_exposer.def(
"ToDense"
, ToDense_function_type( &::gezi::Vector::ToDense )
, ( bp::arg("values_") ) );

}
{ //::gezi::Vector::ToDense

typedef void ( ::gezi::Vector::*ToDense_function_type )(  ) ;

Vector_exposer.def(
"ToDense"
, ToDense_function_type( &::gezi::Vector::ToDense ) );

}
{ //::gezi::Vector::ToSparse

typedef void ( ::gezi::Vector::*ToSparse_function_type )(  ) ;

Vector_exposer.def(
"ToSparse"
, ToSparse_function_type( &::gezi::Vector::ToSparse ) );

}
{ //::gezi::Vector::Value

typedef ::Float ( ::gezi::Vector::*Value_function_type )( int ) const;

Vector_exposer.def(
"Value"
, Value_function_type( &::gezi::Vector::Value )
, ( bp::arg("index") ) );

}
{ //::gezi::Vector::Values

typedef ::std::vector< double > const & ( ::gezi::Vector::*Values_function_type )(  ) const;

Vector_exposer.def(
"Values"
, Values_function_type( &::gezi::Vector::Values )
, bp::return_value_policy< bp::copy_const_reference >() );

}
{ //::gezi::Vector::Values

typedef ::std::vector< double > & ( ::gezi::Vector::*Values_function_type )(  ) ;

Vector_exposer.def(
"Values"
, Values_function_type( &::gezi::Vector::Values )
, bp::return_internal_reference<>());

}
{ //::gezi::Vector::back

typedef ::Float ( ::gezi::Vector::*back_function_type )(  ) ;

Vector_exposer.def(
"back"
, back_function_type( &::gezi::Vector::back ) );

}
{ //::gezi::Vector::clear

typedef void ( ::gezi::Vector::*clear_function_type )(  ) ;

Vector_exposer.def(
"clear"
, clear_function_type( &::gezi::Vector::clear ) );

}
{ //::gezi::Vector::dot

typedef ::Float ( ::gezi::Vector::*dot_function_type )( ::gezi::Vector const & ) const;

Vector_exposer.def(
"dot"
, dot_function_type( &::gezi::Vector::dot )
, ( bp::arg("other") ) );

}
{ //::gezi::Vector::empty

typedef bool ( ::gezi::Vector::*empty_function_type )(  ) const;

Vector_exposer.def(
"empty"
, empty_function_type( &::gezi::Vector::empty ) );

}
{ //::gezi::Vector::erase

typedef void ( ::gezi::Vector::*erase_function_type )( ::__gnu_cxx::__normal_iterator< double*, std::vector< double > > ) ;

Vector_exposer.def(
"erase"
, erase_function_type( &::gezi::Vector::erase )
, ( bp::arg("pos") ) );

}
{ //::gezi::Vector::erase

typedef void ( ::gezi::Vector::*erase_function_type )( ::__gnu_cxx::__normal_iterator< double*, std::vector< double > >,::__gnu_cxx::__normal_iterator< double*, std::vector< double > > ) ;

Vector_exposer.def(
"erase"
, erase_function_type( &::gezi::Vector::erase )
, ( bp::arg("first"), bp::arg("last") ) );

}
{ //::gezi::Vector::front

typedef ::Float ( ::gezi::Vector::*front_function_type )(  ) ;

Vector_exposer.def(
"front"
, front_function_type( &::gezi::Vector::front ) );

}
{ //::gezi::Vector::insert

typedef ::__gnu_cxx::__normal_iterator< double*, std::vector< double > > ( ::gezi::Vector::*insert_function_type )( ::__gnu_cxx::__normal_iterator< double*, std::vector< double > >,::Float const & ) ;

Vector_exposer.def(
"insert"
, insert_function_type( &::gezi::Vector::insert )
, ( bp::arg("position"), bp::arg("val") ) );

}
{ //::gezi::Vector::operator()

typedef ::gezi::Vector & ( ::gezi::Vector::*__call___function_type )( int,::Float ) ;

Vector_exposer.def(
"__call__"
, __call___function_type( &::gezi::Vector::operator() )
, ( bp::arg("index"), bp::arg("value") )
, bp::return_internal_reference<>());

}
Vector_exposer.def( bp::self *= bp::other< Float >() );
Vector_exposer.def( bp::self += bp::self );
Vector_exposer.def( bp::self -= bp::self );
Vector_exposer.def( bp::self /= bp::other< Float >() );
{ //::gezi::Vector::operator=

typedef ::gezi::Vector & ( ::gezi::Vector::*assign_function_type )( ::gezi::Vector const & ) ;

Vector_exposer.def(
"assign"
, assign_function_type( &::gezi::Vector::operator= )
, ( bp::arg("arg0") )
, bp::return_self< >() );

}
{ //::gezi::Vector::operator[]

typedef ::Float ( ::gezi::Vector::*__getitem___function_type )( int ) const;

Vector_exposer.def(
"__getitem__"
, __getitem___function_type( &::gezi::Vector::operator[] )
, ( bp::arg("index") ) );

}
{ //::gezi::Vector::push_back

typedef void ( ::gezi::Vector::*push_back_function_type )( ::Float ) ;

Vector_exposer.def(
"push_back"
, push_back_function_type( &::gezi::Vector::push_back )
, ( bp::arg("item") ) );

}
{ //::gezi::Vector::resize

typedef void ( ::gezi::Vector::*resize_function_type )( int,::Float ) ;

Vector_exposer.def(
"resize"
, resize_function_type( &::gezi::Vector::resize )
, ( bp::arg("length_"), bp::arg("value_")=0 ) );

}
{ //::gezi::Vector::size

typedef ::size_t ( ::gezi::Vector::*size_function_type )(  ) const;

Vector_exposer.def(
"size"
, size_function_type( &::gezi::Vector::size ) );

}
{ //::gezi::Vector::str

typedef ::std::string ( ::gezi::Vector::*str_function_type )( ::std::string ) const;

Vector_exposer.def(
"str"
, str_function_type( &::gezi::Vector::str )
, ( bp::arg("sep")="," ) );

}
Vector_exposer.def_readwrite( "indices", &gezi::Vector::indices );
Vector_exposer.def_readwrite( "keepDense", &gezi::Vector::keepDense );
Vector_exposer.def_readwrite( "keepSparse", &gezi::Vector::keepSparse );
Vector_exposer.def_readwrite( "normalized", &gezi::Vector::normalized );
Vector_exposer.def_readwrite( "numNonZeros", &gezi::Vector::numNonZeros );
Vector_exposer.def_readwrite( "sparsityRatio", &gezi::Vector::sparsityRatio );
Vector_exposer.def_readwrite( "values", &gezi::Vector::values );
}

{ //::gezi::FeatureVector
typedef bp::class_< gezi::FeatureVector, bp::bases< gezi::Vector > > FeatureVector_exposer_t;
FeatureVector_exposer_t FeatureVector_exposer = FeatureVector_exposer_t( "FeatureVector", bp::init< gezi::FeatureVector const & >(( bp::arg("arg0") )) );
bp::scope FeatureVector_scope( FeatureVector_exposer );
{ //::gezi::FeatureVector::Feature
typedef bp::class_< gezi::FeatureVector::Feature > Feature_exposer_t;
Feature_exposer_t Feature_exposer = Feature_exposer_t( "Feature", bp::init< >() );
bp::scope Feature_scope( Feature_exposer );
Feature_exposer.def( bp::init< int, Float >(( bp::arg("index_"), bp::arg("value_") )) );
Feature_exposer.def( bp::init< int >(( bp::arg("index_") )) );
bp::implicitly_convertible< int, gezi::FeatureVector::Feature >();
Feature_exposer.def( bp::self == bp::self );
Feature_exposer.def_readwrite( "index", &gezi::FeatureVector::Feature::index );
Feature_exposer.def_readwrite( "value", &gezi::FeatureVector::Feature::value );
}
VEC_METHOD2(FeatureVector_exposer, gezi::FeatureVector);
FeatureVector_exposer.def( bp::init< bp::optional< bool > >(( bp::arg("useSparse")=(bool)(true) )) );
bp::implicitly_convertible< bool, gezi::FeatureVector >();
FeatureVector_exposer.def( bp::init< int >(( bp::arg("length_") )) );
bp::implicitly_convertible< int, gezi::FeatureVector >();
{ //::gezi::FeatureVector::Str

typedef ::std::string ( ::gezi::FeatureVector::*Str_function_type )( ::std::string ) ;

FeatureVector_exposer.def(
"Str"
, Str_function_type( &::gezi::FeatureVector::Str )
, ( bp::arg("sep")="," ) );

}
{ //::gezi::FeatureVector::add

typedef void ( ::gezi::FeatureVector::*add_function_type )( ::Float,::std::string ) ;

FeatureVector_exposer.def(
"add"
, add_function_type( &::gezi::FeatureVector::add )
, ( bp::arg("value"), bp::arg("name")="" ) );

}
{ //::gezi::FeatureVector::add

typedef void ( ::gezi::FeatureVector::*add_function_type )( ::Float *,int,::std::string ) ;

FeatureVector_exposer.def(
"add"
, add_function_type( &::gezi::FeatureVector::add )
, ( bp::arg("values_"), bp::arg("len"), bp::arg("name")="" ) );

}
{ //::gezi::FeatureVector::add

typedef void ( ::gezi::FeatureVector::*add_function_type )( int,::Float ) ;

FeatureVector_exposer.def(
"add"
, add_function_type( &::gezi::FeatureVector::add )
, ( bp::arg("index"), bp::arg("value") ) );

}
{ //::gezi::FeatureVector::add_section

typedef void ( ::gezi::FeatureVector::*add_section_function_type )( ::std::string ) ;

FeatureVector_exposer.def(
"add_section"
, add_section_function_type( &::gezi::FeatureVector::add_section )
, ( bp::arg("name") ) );

}
{ //::gezi::FeatureVector::at

typedef ::Float ( ::gezi::FeatureVector::*at_function_type )( int ) const;

FeatureVector_exposer.def(
"at"
, at_function_type( &::gezi::FeatureVector::at )
, ( bp::arg("index") ) );

}
{ //::gezi::FeatureVector::clear

typedef void ( ::gezi::FeatureVector::*clear_function_type )(  ) ;

FeatureVector_exposer.def(
"clear"
, clear_function_type( &::gezi::FeatureVector::clear ) );

}
{ //::gezi::FeatureVector::count

typedef int ( ::gezi::FeatureVector::*count_function_type )(  ) const;

FeatureVector_exposer.def(
"count"
, count_function_type( &::gezi::FeatureVector::count ) );

}
{ //::gezi::FeatureVector::dimension

typedef int ( ::gezi::FeatureVector::*dimension_function_type )(  ) const;

FeatureVector_exposer.def(
"dimension"
, dimension_function_type( &::gezi::FeatureVector::dimension ) );

}
{ //::gezi::FeatureVector::empty

typedef bool ( ::gezi::FeatureVector::*empty_function_type )(  ) const;

FeatureVector_exposer.def(
"empty"
, empty_function_type( &::gezi::FeatureVector::empty ) );

}
{ //::gezi::FeatureVector::features

typedef ::std::vector< gezi::FeatureVector::Feature > & ( ::gezi::FeatureVector::*features_function_type )(  ) ;

FeatureVector_exposer.def(
"features"
, features_function_type( &::gezi::FeatureVector::features )
, bp::return_internal_reference<>());

}
{ //::gezi::FeatureVector::features

typedef ::std::vector< gezi::FeatureVector::Feature > const & ( ::gezi::FeatureVector::*features_function_type )(  ) const;

FeatureVector_exposer.def(
"features"
, features_function_type( &::gezi::FeatureVector::features )
, bp::return_value_policy< bp::copy_const_reference >() );

}
{ //::gezi::FeatureVector::finalize

typedef void ( ::gezi::FeatureVector::*finalize_function_type )(  ) ;

FeatureVector_exposer.def(
"finalize"
, finalize_function_type( &::gezi::FeatureVector::finalize ) );

}
{ //::gezi::FeatureVector::name_counts

typedef ::std::vector< int > & ( ::gezi::FeatureVector::*name_counts_function_type )(  ) ;

FeatureVector_exposer.def(
"name_counts"
, name_counts_function_type( &::gezi::FeatureVector::name_counts )
, bp::return_internal_reference<>());

}
{ //::gezi::FeatureVector::name_counts

typedef ::std::vector< int > const & ( ::gezi::FeatureVector::*name_counts_function_type )(  ) const;

FeatureVector_exposer.def(
"name_counts"
, name_counts_function_type( &::gezi::FeatureVector::name_counts )
, bp::return_value_policy< bp::copy_const_reference >() );

}
{ //::gezi::FeatureVector::names

typedef ::std::vector< std::string > & ( ::gezi::FeatureVector::*names_function_type )(  ) ;

FeatureVector_exposer.def(
"names"
, names_function_type( &::gezi::FeatureVector::names )
, bp::return_internal_reference<>());

}
{ //::gezi::FeatureVector::names

typedef ::std::vector< std::string > const & ( ::gezi::FeatureVector::*names_function_type )(  ) const;

FeatureVector_exposer.def(
"names"
, names_function_type( &::gezi::FeatureVector::names )
, bp::return_value_policy< bp::copy_const_reference >() );

}
{ //::gezi::FeatureVector::operator=

typedef ::gezi::FeatureVector & ( ::gezi::FeatureVector::*assign_function_type )( ::gezi::FeatureVector const & ) ;

FeatureVector_exposer.def(
"assign"
, assign_function_type( &::gezi::FeatureVector::operator= )
, ( bp::arg("arg0") )
, bp::return_self< >() );

}
{ //::gezi::FeatureVector::operator[]

typedef ::Float ( ::gezi::FeatureVector::*__getitem___function_type )( int ) const;

FeatureVector_exposer.def(
"__getitem__"
, __getitem___function_type( &::gezi::FeatureVector::operator[] )
, ( bp::arg("i") ) );

}
{ //::gezi::FeatureVector::section_names

typedef ::std::vector< std::string > & ( ::gezi::FeatureVector::*section_names_function_type )(  ) ;

FeatureVector_exposer.def(
"section_names"
, section_names_function_type( &::gezi::FeatureVector::section_names )
, bp::return_internal_reference<>());

}
{ //::gezi::FeatureVector::section_names

typedef ::std::vector< std::string > const & ( ::gezi::FeatureVector::*section_names_function_type )(  ) const;

FeatureVector_exposer.def(
"section_names"
, section_names_function_type( &::gezi::FeatureVector::section_names )
, bp::return_value_policy< bp::copy_const_reference >() );

}
{ //::gezi::FeatureVector::str

typedef ::std::string ( ::gezi::FeatureVector::*str_function_type )( ::std::string ) ;

FeatureVector_exposer.def(
"str"
, str_function_type( &::gezi::FeatureVector::str )
, ( bp::arg("sep")="," ) );

}
{ //::gezi::FeatureVector::value_at

typedef ::Float ( ::gezi::FeatureVector::*value_at_function_type )( int ) const;

FeatureVector_exposer.def(
"value_at"
, value_at_function_type( &::gezi::FeatureVector::value_at )
, ( bp::arg("index") ) );

}
}

bp::class_< gezi::FeaturesExtractorMgr >( "FeaturesExtractorMgr" )
.def(
"add"
, (void ( ::gezi::FeaturesExtractorMgr::* )( ::gezi::FeaturesExtractor * ) )( &::gezi::FeaturesExtractorMgr::add )
, ( bp::arg("extractor") ) )
.def(
"extract"
, (void ( ::gezi::FeaturesExtractorMgr::* )( ::gezi::Features & ) )( &::gezi::FeaturesExtractorMgr::extract )
, ( bp::arg("features") ) )
.def(
"extract"
, (void ( ::gezi::FeaturesExtractorMgr::* )( ::gezi::Features * ) )( &::gezi::FeaturesExtractorMgr::extract )
, ( bp::arg("features") ) )
.def(
"extractor"
, (::gezi::FeaturesExtractor * ( ::gezi::FeaturesExtractorMgr::* )(  ) )( &::gezi::FeaturesExtractorMgr::extractor )
, bp::return_internal_reference<>())
.def(
"extractors"
, (::std::vector< gezi::FeaturesExtractor* > & ( ::gezi::FeaturesExtractorMgr::* )(  ) )( &::gezi::FeaturesExtractorMgr::extractors )
, bp::return_internal_reference<>())
.def(
"extractors"
, (::std::vector< gezi::FeaturesExtractor* > const & ( ::gezi::FeaturesExtractorMgr::* )(  ) const)( &::gezi::FeaturesExtractorMgr::extractors )
, bp::return_value_policy< bp::copy_const_reference >() );

bp::class_< gezi::Identifer >( "Identifer" )
.def(
"Load"
, (void ( ::gezi::Identifer::* )( ::std::string ) )( &::gezi::Identifer::Load )
, ( bp::arg("path") ) )
.def(
"Save"
, (void ( ::gezi::Identifer::* )( ::std::string ) )( &::gezi::Identifer::Save )
, ( bp::arg("path") ) )
.def(
"add"
, (int ( ::gezi::Identifer::* )( ::std::string ) )( &::gezi::Identifer::add )
, ( bp::arg("f") ) )
.def(
"add"
, (int ( ::gezi::Identifer::* )( ::std::string,bool & ) )( &::gezi::Identifer::add )
, ( bp::arg("f"), bp::arg("isnew") ) )
.def(
"add_unique"
, (int ( ::gezi::Identifer::* )( ::std::string ) )( &::gezi::Identifer::add_unique )
, ( bp::arg("f") ) )
.def(
"clear"
, (void ( ::gezi::Identifer::* )(  ) )( &::gezi::Identifer::clear ) )
.def(
"empty"
, (bool ( ::gezi::Identifer::* )(  ) const)( &::gezi::Identifer::empty ) )
.def(
"has"
, (bool ( ::gezi::Identifer::* )( ::std::string ) const)( &::gezi::Identifer::has )
, ( bp::arg("f") ) )
.def(
"id"
, (int ( ::gezi::Identifer::* )( ::std::string ) const)( &::gezi::Identifer::id )
, ( bp::arg("f") ) )
.def(
"key"
, (::std::string ( ::gezi::Identifer::* )( int ) const)( &::gezi::Identifer::key )
, ( bp::arg("id") ) )
.def(
"keys"
, (::std::vector< std::string > & ( ::gezi::Identifer::* )(  ) )( &::gezi::Identifer::keys )
, bp::return_internal_reference<>())
.def(
"last"
, (::std::string ( ::gezi::Identifer::* )(  ) )( &::gezi::Identifer::last ) )
.def(
"load"
, (bool ( ::gezi::Identifer::* )( ::std::string,::std::string ) )( &::gezi::Identifer::load )
, ( bp::arg("file"), bp::arg("sep")="\011" ) )
.def(
"null_id"
, (int const (*)(  ))( &::gezi::Identifer::null_id ) )
.def(
"__call__"
, (int const ( ::gezi::Identifer::* )( ::std::string ) const)( &::gezi::Identifer::operator() )
, ( bp::arg("key") ) )
.def(
"__getitem__"
, (::std::string ( ::gezi::Identifer::* )( int ) const)( &::gezi::Identifer::operator[] )
, ( bp::arg("id") ) )
.def(
"save"
, (void ( ::gezi::Identifer::* )( ::std::string ) )( &::gezi::Identifer::save )
, ( bp::arg("file") ) )
.def(
"size"
, (::size_t ( ::gezi::Identifer::* )(  ) const)( &::gezi::Identifer::size ) )
.def(
"words"
, (::std::vector< std::string > & ( ::gezi::Identifer::* )(  ) )( &::gezi::Identifer::words )
, bp::return_internal_reference<>())
.def_readonly( "NullId", gezi::Identifer::NullId )
.staticmethod( "null_id" );

{ //::gezi::Predictor
typedef bp::class_< Predictor_wrapper > Predictor_exposer_t;
Predictor_exposer_t Predictor_exposer = Predictor_exposer_t( "Predictor", bp::init< >() );
bp::scope Predictor_scope( Predictor_exposer );
Predictor_exposer.def( bp::init< gezi::NormalizerPtr, gezi::CalibratorPtr, gezi::FeatureNamesVector const & >(( bp::arg("normalizer"), bp::arg("calibrator"), bp::arg("featureNames") )) );
Predictor_exposer.def( bp::init< gezi::CalibratorPtr, gezi::FeatureNamesVector const & >(( bp::arg("calibrator"), bp::arg("featureNames") )) );
Predictor_exposer.def( bp::init< gezi::FeatureNamesVector const & >(( bp::arg("featureNames") )) );
bp::implicitly_convertible< gezi::FeatureNamesVector const &, gezi::Predictor >();
{ //::gezi::Predictor::CustomLoad

typedef bool ( ::gezi::Predictor::*CustomLoad_function_type )( ::std::string ) ;
typedef bool ( Predictor_wrapper::*default_CustomLoad_function_type )( ::std::string ) ;

Predictor_exposer.def(
"CustomLoad"
, CustomLoad_function_type(&::gezi::Predictor::CustomLoad)
, default_CustomLoad_function_type(&Predictor_wrapper::default_CustomLoad)
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::CustomLoad_

typedef bool ( ::gezi::Predictor::*CustomLoad__function_type )( ::std::string ) ;
typedef bool ( Predictor_wrapper::*default_CustomLoad__function_type )( ::std::string ) ;

Predictor_exposer.def(
"CustomLoad_"
, CustomLoad__function_type(&::gezi::Predictor::CustomLoad_)
, default_CustomLoad__function_type(&Predictor_wrapper::default_CustomLoad_)
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::CustomSave

typedef void ( ::gezi::Predictor::*CustomSave_function_type )(  ) ;
typedef void ( Predictor_wrapper::*default_CustomSave_function_type )(  ) ;

Predictor_exposer.def(
"CustomSave"
, CustomSave_function_type(&::gezi::Predictor::CustomSave)
, default_CustomSave_function_type(&Predictor_wrapper::default_CustomSave) );

}
{ //::gezi::Predictor::CustomSave

typedef void ( ::gezi::Predictor::*CustomSave_function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_CustomSave_function_type )( ::std::string ) ;

Predictor_exposer.def(
"CustomSave"
, CustomSave_function_type(&::gezi::Predictor::CustomSave)
, default_CustomSave_function_type(&Predictor_wrapper::default_CustomSave)
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::CustomSave_

typedef void ( ::gezi::Predictor::*CustomSave__function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_CustomSave__function_type )( ::std::string ) ;

Predictor_exposer.def(
"CustomSave_"
, CustomSave__function_type(&::gezi::Predictor::CustomSave_)
, default_CustomSave__function_type(&Predictor_wrapper::default_CustomSave_)
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::GetCalibrator

typedef ::gezi::CalibratorPtr & ( ::gezi::Predictor::*GetCalibrator_function_type )(  ) ;

Predictor_exposer.def(
"GetCalibrator"
, GetCalibrator_function_type( &::gezi::Predictor::GetCalibrator )
, bp::return_internal_reference<>());

}
{ //::gezi::Predictor::GetNormalizer

typedef ::gezi::NormalizerPtr & ( ::gezi::Predictor::*GetNormalizer_function_type )(  ) ;

Predictor_exposer.def(
"GetNormalizer"
, GetNormalizer_function_type( &::gezi::Predictor::GetNormalizer )
, bp::return_internal_reference<>());

}
{ //::gezi::Predictor::GetParam

typedef ::std::string ( ::gezi::Predictor::*GetParam_function_type )(  ) ;

Predictor_exposer.def(
"GetParam"
, GetParam_function_type( &::gezi::Predictor::GetParam ) );

}
{ //::gezi::Predictor::GetPredictionKind

typedef ::gezi::PredictionKind ( ::gezi::Predictor::*GetPredictionKind_function_type )(  ) ;
typedef ::gezi::PredictionKind ( Predictor_wrapper::*default_GetPredictionKind_function_type )(  ) ;

Predictor_exposer.def(
"GetPredictionKind"
, GetPredictionKind_function_type(&::gezi::Predictor::GetPredictionKind)
, default_GetPredictionKind_function_type(&Predictor_wrapper::default_GetPredictionKind) );

}
{ //::gezi::Predictor::Load

typedef bool ( ::gezi::Predictor::*Load_function_type )( ::std::string ) ;
typedef bool ( Predictor_wrapper::*default_Load_function_type )( ::std::string ) ;

Predictor_exposer.def(
"Load"
, Load_function_type(&::gezi::Predictor::Load)
, default_Load_function_type(&Predictor_wrapper::default_Load)
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::LoadBin

typedef bool ( ::gezi::Predictor::*LoadBin_function_type )( ::std::string ) ;
typedef bool ( Predictor_wrapper::*default_LoadBin_function_type )( ::std::string ) ;

Predictor_exposer.def(
"LoadBin"
, LoadBin_function_type(&::gezi::Predictor::LoadBin)
, default_LoadBin_function_type(&Predictor_wrapper::default_LoadBin)
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::LoadNormalizerAndCalibrator

typedef bool ( ::gezi::Predictor::*LoadNormalizerAndCalibrator_function_type )( ::std::string ) ;

Predictor_exposer.def(
"LoadNormalizerAndCalibrator"
, LoadNormalizerAndCalibrator_function_type( &::gezi::Predictor::LoadNormalizerAndCalibrator )
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::LoadText

typedef bool ( ::gezi::Predictor::*LoadText_function_type )( ::std::string ) ;
typedef bool ( Predictor_wrapper::*default_LoadText_function_type )( ::std::string ) ;

Predictor_exposer.def(
"LoadText"
, LoadText_function_type(&::gezi::Predictor::LoadText)
, default_LoadText_function_type(&Predictor_wrapper::default_LoadText)
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::LoadText_

typedef bool ( ::gezi::Predictor::*LoadText__function_type )( ::std::string ) ;
typedef bool ( Predictor_wrapper::*default_LoadText__function_type )( ::std::string ) ;

Predictor_exposer.def(
"LoadText_"
, LoadText__function_type(&::gezi::Predictor::LoadText_)
, default_LoadText__function_type(&Predictor_wrapper::default_LoadText_)
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::Load_

typedef bool ( ::gezi::Predictor::*Load__function_type )( ::std::string ) ;
typedef bool ( Predictor_wrapper::*default_Load__function_type )( ::std::string ) ;

Predictor_exposer.def(
"Load_"
, Load__function_type(&::gezi::Predictor::Load_)
, default_Load__function_type(&Predictor_wrapper::default_Load_)
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::Margin

typedef ::Float ( Predictor_wrapper::*Margin_function_type )( ::gezi::Vector & ) ;

Predictor_exposer.def(
"Margin"
, Margin_function_type( &Predictor_wrapper::Margin )
, ( bp::arg("features") ) );

}
{ //::gezi::Predictor::Name

typedef ::std::string ( ::gezi::Predictor::*Name_function_type )(  ) ;
typedef ::std::string ( Predictor_wrapper::*default_Name_function_type )(  ) ;

Predictor_exposer.def(
"Name"
, Name_function_type(&::gezi::Predictor::Name)
, default_Name_function_type(&Predictor_wrapper::default_Name) );

}
{ //::gezi::Predictor::Output

typedef ::Float ( ::gezi::Predictor::*Output_function_type )( ::gezi::Instance & ) ;

Predictor_exposer.def(
"Output"
, Output_function_type( &::gezi::Predictor::Output )
, ( bp::arg("instance") ) );

}
{ //::gezi::Predictor::Output

typedef ::Float ( ::gezi::Predictor::*Output_function_type )( ::gezi::InstancePtr ) ;
typedef ::Float ( Predictor_wrapper::*default_Output_function_type )( ::gezi::InstancePtr ) ;

Predictor_exposer.def(
"Output"
, Output_function_type(&::gezi::Predictor::Output)
, default_Output_function_type(&Predictor_wrapper::default_Output)
, ( bp::arg("instance") ) );

}
{ //::gezi::Predictor::Output

typedef ::Float ( ::gezi::Predictor::*Output_function_type )( ::gezi::Vector & ) ;

Predictor_exposer.def(
"Output"
, Output_function_type( &::gezi::Predictor::Output )
, ( bp::arg("features") ) );

}
{ //::gezi::Predictor::Output

typedef ::Float ( ::gezi::Predictor::*Output_function_type )( ::Fvec & ) ;

Predictor_exposer.def(
"Output"
, Output_function_type( &::gezi::Predictor::Output )
, ( bp::arg("values") ) );

}
{ //::gezi::Predictor::Output

typedef ::Float ( ::gezi::Predictor::*Output_function_type )( ::ivec &,::Fvec & ) ;

Predictor_exposer.def(
"Output"
, Output_function_type( &::gezi::Predictor::Output )
, ( bp::arg("indices"), bp::arg("values") ) );

}
{ //::gezi::Predictor::Output

typedef ::Float ( ::gezi::Predictor::*Output_function_type )( ::std::string ) ;
typedef ::Float ( Predictor_wrapper::*default_Output_function_type )( ::std::string ) ;

Predictor_exposer.def(
"Output"
, Output_function_type(&::gezi::Predictor::Output)
, default_Output_function_type(&Predictor_wrapper::default_Output)
, ( bp::arg("line") ) );

}
{ //::gezi::Predictor::Output

typedef ::Float ( ::gezi::Predictor::*Output_function_type )( ::std::map< int, double > const & ) ;

Predictor_exposer.def(
"Output"
, Output_function_type( &::gezi::Predictor::Output )
, ( bp::arg("m") ) );

}
{ //::gezi::Predictor::Path

typedef ::std::string ( ::gezi::Predictor::*Path_function_type )(  ) ;

Predictor_exposer.def(
"Path"
, Path_function_type( &::gezi::Predictor::Path ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::gezi::Instance & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("instance") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::Fvec & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("values") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::ivec &,::Fvec & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("indices"), bp::arg("values") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::std::string,::Float & ) ;
typedef ::Float ( Predictor_wrapper::*default_Predict_function_type )( ::std::string,::Float & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type(&::gezi::Predictor::Predict)
, default_Predict_function_type(&Predictor_wrapper::default_Predict)
, ( bp::arg("line"), bp::arg("output") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::gezi::InstancePtr ) ;
typedef ::Float ( Predictor_wrapper::*default_Predict_function_type )( ::gezi::InstancePtr ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type(&::gezi::Predictor::Predict)
, default_Predict_function_type(&Predictor_wrapper::default_Predict)
, ( bp::arg("instance") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::gezi::Vector & ) ;
typedef ::Float ( Predictor_wrapper::*default_Predict_function_type )( ::gezi::Vector & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type(&::gezi::Predictor::Predict)
, default_Predict_function_type(&Predictor_wrapper::default_Predict)
, ( bp::arg("features") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::gezi::Instance &,::Float & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("instance"), bp::arg("output") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::gezi::InstancePtr,::Float & ) ;
typedef ::Float ( Predictor_wrapper::*default_Predict_function_type )( ::gezi::InstancePtr,::Float & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type(&::gezi::Predictor::Predict)
, default_Predict_function_type(&Predictor_wrapper::default_Predict)
, ( bp::arg("instance"), bp::arg("output") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::gezi::Vector &,::Float & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("features"), bp::arg("output") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::Fvec &,::Float & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("values"), bp::arg("output") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::ivec &,::Fvec &,::Float & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("indices"), bp::arg("values"), bp::arg("output") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::std::map< int, double > const & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("m") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::std::map< int, double > const &,::Float & ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("m"), bp::arg("output") ) );

}
{ //::gezi::Predictor::Predict

typedef ::Float ( ::gezi::Predictor::*Predict_function_type )( ::Float ) ;

Predictor_exposer.def(
"Predict"
, Predict_function_type( &::gezi::Predictor::Predict )
, ( bp::arg("output") ) );

}
{ //::gezi::Predictor::ReadPathAndSetParam_

typedef void ( ::gezi::Predictor::*ReadPathAndSetParam__function_type )( ::std::string ) ;

Predictor_exposer.def(
"ReadPathAndSetParam_"
, ReadPathAndSetParam__function_type( &::gezi::Predictor::ReadPathAndSetParam_ )
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::Save

typedef void ( ::gezi::Predictor::*Save_function_type )(  ) ;
typedef void ( Predictor_wrapper::*default_Save_function_type )(  ) ;

Predictor_exposer.def(
"Save"
, Save_function_type(&::gezi::Predictor::Save)
, default_Save_function_type(&Predictor_wrapper::default_Save) );

}
{ //::gezi::Predictor::Save

typedef void ( ::gezi::Predictor::*Save_function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_Save_function_type )( ::std::string ) ;

Predictor_exposer.def(
"Save"
, Save_function_type(&::gezi::Predictor::Save)
, default_Save_function_type(&Predictor_wrapper::default_Save)
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::SaveBin

typedef void ( ::gezi::Predictor::*SaveBin_function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_SaveBin_function_type )( ::std::string ) ;

Predictor_exposer.def(
"SaveBin"
, SaveBin_function_type(&::gezi::Predictor::SaveBin)
, default_SaveBin_function_type(&Predictor_wrapper::default_SaveBin)
, ( bp::arg("path") ) );

}
{ //::gezi::Predictor::SaveCode

typedef void ( ::gezi::Predictor::*SaveCode_function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_SaveCode_function_type )( ::std::string ) ;

Predictor_exposer.def(
"SaveCode"
, SaveCode_function_type(&::gezi::Predictor::SaveCode)
, default_SaveCode_function_type(&Predictor_wrapper::default_SaveCode)
, ( bp::arg("codeTypeStr")="cpp" ) );

}
{ //::gezi::Predictor::SaveCode_

typedef void ( ::gezi::Predictor::*SaveCode__function_type )( ::std::string,::gezi::CodeType ) ;
typedef void ( Predictor_wrapper::*default_SaveCode__function_type )( ::std::string,::gezi::CodeType ) ;

Predictor_exposer.def(
"SaveCode_"
, SaveCode__function_type(&::gezi::Predictor::SaveCode_)
, default_SaveCode__function_type(&Predictor_wrapper::default_SaveCode_)
, ( bp::arg("file"), bp::arg("codeType") ) );

}
{ //::gezi::Predictor::SaveFeaturesGain

typedef void ( ::gezi::Predictor::*SaveFeaturesGain_function_type )( int ) ;
typedef void ( Predictor_wrapper::*default_SaveFeaturesGain_function_type )( int ) ;

Predictor_exposer.def(
"SaveFeaturesGain"
, SaveFeaturesGain_function_type(&::gezi::Predictor::SaveFeaturesGain)
, default_SaveFeaturesGain_function_type(&Predictor_wrapper::default_SaveFeaturesGain)
, ( bp::arg("topNum")=(int)(0) ) );

}
{ //::gezi::Predictor::SaveJson

typedef void ( ::gezi::Predictor::*SaveJson_function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_SaveJson_function_type )( ::std::string ) ;

Predictor_exposer.def(
"SaveJson"
, SaveJson_function_type(&::gezi::Predictor::SaveJson)
, default_SaveJson_function_type(&Predictor_wrapper::default_SaveJson)
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::SaveJson

typedef void ( ::gezi::Predictor::*SaveJson_function_type )(  ) ;

Predictor_exposer.def(
"SaveJson"
, SaveJson_function_type( &::gezi::Predictor::SaveJson ) );

}
{ //::gezi::Predictor::SaveJson_

typedef void ( ::gezi::Predictor::*SaveJson__function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_SaveJson__function_type )( ::std::string ) ;

Predictor_exposer.def(
"SaveJson_"
, SaveJson__function_type(&::gezi::Predictor::SaveJson_)
, default_SaveJson__function_type(&Predictor_wrapper::default_SaveJson_)
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::SaveText

typedef void ( ::gezi::Predictor::*SaveText_function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_SaveText_function_type )( ::std::string ) ;

Predictor_exposer.def(
"SaveText"
, SaveText_function_type(&::gezi::Predictor::SaveText)
, default_SaveText_function_type(&Predictor_wrapper::default_SaveText)
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::SaveText

typedef void ( ::gezi::Predictor::*SaveText_function_type )(  ) ;

Predictor_exposer.def(
"SaveText"
, SaveText_function_type( &::gezi::Predictor::SaveText ) );

}
{ //::gezi::Predictor::SaveText_

typedef void ( ::gezi::Predictor::*SaveText__function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_SaveText__function_type )( ::std::string ) ;

Predictor_exposer.def(
"SaveText_"
, SaveText__function_type(&::gezi::Predictor::SaveText_)
, default_SaveText__function_type(&Predictor_wrapper::default_SaveText_)
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::SaveXml

typedef void ( ::gezi::Predictor::*SaveXml_function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_SaveXml_function_type )( ::std::string ) ;

Predictor_exposer.def(
"SaveXml"
, SaveXml_function_type(&::gezi::Predictor::SaveXml)
, default_SaveXml_function_type(&Predictor_wrapper::default_SaveXml)
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::SaveXml

typedef void ( ::gezi::Predictor::*SaveXml_function_type )(  ) ;

Predictor_exposer.def(
"SaveXml"
, SaveXml_function_type( &::gezi::Predictor::SaveXml ) );

}
{ //::gezi::Predictor::SaveXml_

typedef void ( ::gezi::Predictor::*SaveXml__function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_SaveXml__function_type )( ::std::string ) ;

Predictor_exposer.def(
"SaveXml_"
, SaveXml__function_type(&::gezi::Predictor::SaveXml_)
, default_SaveXml__function_type(&Predictor_wrapper::default_SaveXml_)
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::Save_

typedef void ( ::gezi::Predictor::*Save__function_type )( ::std::string ) ;
typedef void ( Predictor_wrapper::*default_Save__function_type )( ::std::string ) ;

Predictor_exposer.def(
"Save_"
, Save__function_type(&::gezi::Predictor::Save_)
, default_Save__function_type(&Predictor_wrapper::default_Save_)
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::SetCalibrator

typedef void ( ::gezi::Predictor::*SetCalibrator_function_type )( ::gezi::CalibratorPtr ) ;

Predictor_exposer.def(
"SetCalibrator"
, SetCalibrator_function_type( &::gezi::Predictor::SetCalibrator )
, ( bp::arg("calibrator") ) );

}
{ //::gezi::Predictor::SetFeatureGainVec

typedef void ( ::gezi::Predictor::*SetFeatureGainVec_function_type )( ::std::vector< double > const & ) ;

Predictor_exposer.def(
"SetFeatureGainVec"
, SetFeatureGainVec_function_type( &::gezi::Predictor::SetFeatureGainVec )
, ( bp::arg("featureGainVec") ) );

}
{ //::gezi::Predictor::SetFeatureNames

typedef void ( ::gezi::Predictor::*SetFeatureNames_function_type )( ::gezi::FeatureNamesVector const & ) ;

Predictor_exposer.def(
"SetFeatureNames"
, SetFeatureNames_function_type( &::gezi::Predictor::SetFeatureNames )
, ( bp::arg("featureNames") ) );

}
{ //::gezi::Predictor::SetLoadNormalizerAndCalibrator

typedef void ( *SetLoadNormalizerAndCalibrator_function_type )( bool );

Predictor_exposer.def(
"SetLoadNormalizerAndCalibrator"
, SetLoadNormalizerAndCalibrator_function_type( &::gezi::Predictor::SetLoadNormalizerAndCalibrator )
, ( bp::arg("loadNormalizerAndCalibrator_")=(bool)(true) ) );

}
{ //::gezi::Predictor::SetNormalizeCopy

typedef ::gezi::Predictor & ( ::gezi::Predictor::*SetNormalizeCopy_function_type )( bool ) ;

Predictor_exposer.def(
"SetNormalizeCopy"
, SetNormalizeCopy_function_type( &::gezi::Predictor::SetNormalizeCopy )
, ( bp::arg("normalizeCopy")=(bool)(true) )
, bp::return_internal_reference<>());

}
{ //::gezi::Predictor::SetNormalizer

typedef void ( ::gezi::Predictor::*SetNormalizer_function_type )( ::gezi::NormalizerPtr ) ;

Predictor_exposer.def(
"SetNormalizer"
, SetNormalizer_function_type( &::gezi::Predictor::SetNormalizer )
, ( bp::arg("normalizer") ) );

}
{ //::gezi::Predictor::SetParam

typedef ::gezi::Predictor & ( ::gezi::Predictor::*SetParam_function_type )( ::std::string ) ;

Predictor_exposer.def(
"SetParam"
, SetParam_function_type( &::gezi::Predictor::SetParam )
, ( bp::arg("param") )
, bp::return_internal_reference<>());

}
{ //::gezi::Predictor::SetPath

typedef ::gezi::Predictor & ( ::gezi::Predictor::*SetPath_function_type )( ::std::string ) ;

Predictor_exposer.def(
"SetPath"
, SetPath_function_type( &::gezi::Predictor::SetPath )
, ( bp::arg("path") )
, bp::return_internal_reference<>());

}
{ //::gezi::Predictor::SetSaveCalibratorText

typedef ::gezi::Predictor & ( ::gezi::Predictor::*SetSaveCalibratorText_function_type )( bool ) ;

Predictor_exposer.def(
"SetSaveCalibratorText"
, SetSaveCalibratorText_function_type( &::gezi::Predictor::SetSaveCalibratorText )
, ( bp::arg("setSave")=(bool)(true) )
, bp::return_internal_reference<>());

}
{ //::gezi::Predictor::SetSaveNormalizerText

typedef ::gezi::Predictor & ( ::gezi::Predictor::*SetSaveNormalizerText_function_type )( bool ) ;

Predictor_exposer.def(
"SetSaveNormalizerText"
, SetSaveNormalizerText_function_type( &::gezi::Predictor::SetSaveNormalizerText )
, ( bp::arg("setSave")=(bool)(true) )
, bp::return_internal_reference<>());

}
{ //::gezi::Predictor::SetUseCustomModel

typedef ::gezi::Predictor & ( ::gezi::Predictor::*SetUseCustomModel_function_type )( bool ) ;

Predictor_exposer.def(
"SetUseCustomModel"
, SetUseCustomModel_function_type( &::gezi::Predictor::SetUseCustomModel )
, ( bp::arg("useCustomModel") )
, bp::return_internal_reference<>());

}
{ //::gezi::Predictor::ThirdModelName

typedef ::std::string ( *ThirdModelName_function_type )( ::std::string );

Predictor_exposer.def(
"ThirdModelName"
, ThirdModelName_function_type( &::gezi::Predictor::ThirdModelName )
, ( bp::arg("file") ) );

}
{ //::gezi::Predictor::ToFeaturesGainSummary

typedef ::std::string ( ::gezi::Predictor::*ToFeaturesGainSummary_function_type )( int ) ;
typedef ::std::string ( Predictor_wrapper::*default_ToFeaturesGainSummary_function_type )( int ) ;

Predictor_exposer.def(
"ToFeaturesGainSummary"
, ToFeaturesGainSummary_function_type(&::gezi::Predictor::ToFeaturesGainSummary)
, default_ToFeaturesGainSummary_function_type(&Predictor_wrapper::default_ToFeaturesGainSummary)
, ( bp::arg("topNum")=(int)(0) ) );

}
{ //::gezi::Predictor::ToGainSummary

typedef ::std::string ( ::gezi::Predictor::*ToGainSummary_function_type )( ::gezi::Vector & ) ;
typedef ::std::string ( Predictor_wrapper::*default_ToGainSummary_function_type )( ::gezi::Vector & ) ;

Predictor_exposer.def(
"ToGainSummary"
, ToGainSummary_function_type(&::gezi::Predictor::ToGainSummary)
, default_ToGainSummary_function_type(&Predictor_wrapper::default_ToGainSummary)
, ( bp::arg("features") ) );

}
{ //::gezi::Predictor::ToNamedFeatures

typedef ::std::map< std::string, double > ( ::gezi::Predictor::*ToNamedFeatures_function_type )( ::gezi::Vector const & ) ;

Predictor_exposer.def(
"ToNamedFeatures"
, ToNamedFeatures_function_type( &::gezi::Predictor::ToNamedFeatures )
, ( bp::arg("features") ) );

}
{ //::gezi::Predictor::UseCustomModel

typedef bool ( ::gezi::Predictor::*UseCustomModel_function_type )(  ) const;

Predictor_exposer.def(
"UseCustomModel"
, UseCustomModel_function_type( &::gezi::Predictor::UseCustomModel ) );

}
Predictor_exposer.staticmethod( "SetLoadNormalizerAndCalibrator" );
Predictor_exposer.staticmethod( "ThirdModelName" );
bp::register_ptr_to_python< std::shared_ptr< gezi::Predictor > >();
bp::implicitly_convertible< std::shared_ptr< gezi::Predictor >, std::shared_ptr< gezi::LoadSave > >();
}

bp::class_< gezi::PredictorFactory >( "PredictorFactory" )
.def(
"CreatePredictor"
, (::gezi::PredictorPtr (*)( ::std::string ))( &::gezi::PredictorFactory::CreatePredictor )
, ( bp::arg("name") ) )
.def(
"CreatePredictor"
, (::gezi::PredictorPtr (*)( ::std::string,::std::string ))( &::gezi::PredictorFactory::CreatePredictor )
, ( bp::arg("name"), bp::arg("path") ) )
.def(
"CreatePredictorFromTextFormat"
, (::gezi::PredictorPtr (*)( ::std::string,::std::string ))( &::gezi::PredictorFactory::CreatePredictorFromTextFormat )
, ( bp::arg("name"), bp::arg("path") ) )
.def(
"LoadPredictor"
, (::gezi::PredictorPtr (*)( ::std::string,bool ))( &::gezi::PredictorFactory::LoadPredictor )
, ( bp::arg("path"), bp::arg("useCustomModel")=(bool)(false) ) )
.def(
"LoadPredictors"
, (::gezi::Predictors (*)( ::svec const & ))( &::gezi::PredictorFactory::LoadPredictors )
, ( bp::arg("paths") ) )
.def(
"LoadTextPredictor"
, (::gezi::PredictorPtr (*)( ::std::string ))( &::gezi::PredictorFactory::LoadTextPredictor )
, ( bp::arg("path") ) )
.staticmethod( "CreatePredictor" )
.staticmethod( "CreatePredictorFromTextFormat" )
.staticmethod( "LoadPredictor" )
.staticmethod( "LoadPredictors" )
.staticmethod( "LoadTextPredictor" );

bp::class_< gezi::PyFeatures, bp::bases< gezi::FeatureVector > >( "PyFeatures" );

bp::class_< gezi::ValueIdentifer< double >, bp::bases< gezi::Identifer > >( "DoubleIdentifer" )
.def(
"Load"
, (void ( ::gezi::ValueIdentifer<double>::* )( ::std::string ) )( &::gezi::ValueIdentifer< double >::Load )
, ( bp::arg("file") ) )
.def(
"Save"
, (void ( ::gezi::ValueIdentifer<double>::* )( ::std::string ) )( &::gezi::ValueIdentifer< double >::Save )
, ( bp::arg("file") ) )
.def(
"get_value"
, (double ( ::gezi::ValueIdentifer<double>::* )( ::std::string ) const)( &::gezi::ValueIdentifer< double >::get_value )
, ( bp::arg("key") ) )
.def(
"load"
, (bool ( ::gezi::ValueIdentifer<double>::* )( ::std::string,int,::std::string ) )( &::gezi::ValueIdentifer< double >::load )
, ( bp::arg("file"), bp::arg("index")=(int)(1), bp::arg("sep")="\011" ) )
.def(
"value"
, (double ( ::gezi::ValueIdentifer<double>::* )( int ) const)( &::gezi::ValueIdentifer< double >::value )
, ( bp::arg("index") ) );

//    bp::class_< gezi::PyHack_DoubleIdentifer, bp::bases< gezi::ValueIdentifer< double > > >( "PyHack_DoubleIdentifer" );

bp::class_< gezi::ValueIdentifer< int >, bp::bases< gezi::Identifer > >( "IntIdentifer" )
.def(
"Load"
, (void ( ::gezi::ValueIdentifer<int>::* )( ::std::string ) )( &::gezi::ValueIdentifer< int >::Load )
, ( bp::arg("file") ) )
.def(
"Save"
, (void ( ::gezi::ValueIdentifer<int>::* )( ::std::string ) )( &::gezi::ValueIdentifer< int >::Save )
, ( bp::arg("file") ) )
.def(
"get_value"
, (int ( ::gezi::ValueIdentifer<int>::* )( ::std::string ) const)( &::gezi::ValueIdentifer< int >::get_value )
, ( bp::arg("key") ) )
.def(
"load"
, (bool ( ::gezi::ValueIdentifer<int>::* )( ::std::string,int,::std::string ) )( &::gezi::ValueIdentifer< int >::load )
, ( bp::arg("file"), bp::arg("index")=(int)(1), bp::arg("sep")="\011" ) )
.def(
"value"
, (int ( ::gezi::ValueIdentifer<int>::* )( int ) const)( &::gezi::ValueIdentifer< int >::value )
, ( bp::arg("index") ) );

//    bp::class_< gezi::PyHack_IntIndentifer, bp::bases< gezi::ValueIdentifer< int > > >( "PyHack_IntIndentifer" );

{ //::gezi::WeightVector
typedef bp::class_< gezi::WeightVector, bp::bases< gezi::Vector > > WeightVector_exposer_t;
WeightVector_exposer_t WeightVector_exposer = WeightVector_exposer_t( "WeightVector", bp::init< >() );
bp::scope WeightVector_scope( WeightVector_exposer );
WeightVector_exposer.def( bp::init< int >(( bp::arg("length_") )) );
bp::implicitly_convertible< int, gezi::WeightVector >();
WeightVector_exposer.def( bp::init< int, Float >(( bp::arg("length_"), bp::arg("val") )) );
{ //::gezi::WeightVector::Add

typedef void ( ::gezi::WeightVector::*Add_function_type )( ::gezi::Vector const & ) ;

WeightVector_exposer.def(
"Add"
, Add_function_type( &::gezi::WeightVector::Add )
, ( bp::arg("other") ) );

}
{ //::gezi::WeightVector::AddScale

typedef void ( ::gezi::WeightVector::*AddScale_function_type )( ::gezi::Vector const &,::Float ) ;

WeightVector_exposer.def(
"AddScale"
, AddScale_function_type( &::gezi::WeightVector::AddScale )
, ( bp::arg("other"), bp::arg("scale") ) );

}
{ //::gezi::WeightVector::AddSparse

typedef void ( ::gezi::WeightVector::*AddSparse_function_type )( ::gezi::Vector const & ) ;

WeightVector_exposer.def(
"AddSparse"
, AddSparse_function_type( &::gezi::WeightVector::AddSparse )
, ( bp::arg("other") ) );

}
{ //::gezi::WeightVector::Init

typedef void ( ::gezi::WeightVector::*Init_function_type )( int,::Float ) ;

WeightVector_exposer.def(
"Init"
, Init_function_type( &::gezi::WeightVector::Init )
, ( bp::arg("length_"), bp::arg("val") ) );

}
{ //::gezi::WeightVector::Norm

typedef ::Float ( ::gezi::WeightVector::*Norm_function_type )(  ) ;

WeightVector_exposer.def(
"Norm"
, Norm_function_type( &::gezi::WeightVector::Norm ) );

}
{ //::gezi::WeightVector::Resize

typedef void ( ::gezi::WeightVector::*Resize_function_type )( int,::Float ) ;

WeightVector_exposer.def(
"Resize"
, Resize_function_type( &::gezi::WeightVector::Resize )
, ( bp::arg("length_"), bp::arg("value_")=0 ) );

}
{ //::gezi::WeightVector::ScaleBy

typedef void ( ::gezi::WeightVector::*ScaleBy_function_type )( ::Float ) ;

WeightVector_exposer.def(
"ScaleBy"
, ScaleBy_function_type( &::gezi::WeightVector::ScaleBy )
, ( bp::arg("scalingFactor") ) );

}
{ //::gezi::WeightVector::ScaleToOne

typedef void ( ::gezi::WeightVector::*ScaleToOne_function_type )(  ) ;

WeightVector_exposer.def(
"ScaleToOne"
, ScaleToOne_function_type( &::gezi::WeightVector::ScaleToOne ) );

}
{ //::gezi::WeightVector::SetLength

typedef void ( ::gezi::WeightVector::*SetLength_function_type )( int ) ;

WeightVector_exposer.def(
"SetLength"
, SetLength_function_type( &::gezi::WeightVector::SetLength )
, ( bp::arg("length_") ) );

}
{ //::gezi::WeightVector::Sparsify

typedef void ( ::gezi::WeightVector::*Sparsify_function_type )( ::Float ) ;

WeightVector_exposer.def(
"Sparsify"
, Sparsify_function_type( &::gezi::WeightVector::Sparsify )
, ( bp::arg("maxSparsity") ) );

}
{ //::gezi::WeightVector::Sparsify

typedef void ( ::gezi::WeightVector::*Sparsify_function_type )(  ) ;

WeightVector_exposer.def(
"Sparsify"
, Sparsify_function_type( &::gezi::WeightVector::Sparsify ) );

}
{ //::gezi::WeightVector::SquaredNorm

typedef ::Float ( ::gezi::WeightVector::*SquaredNorm_function_type )(  ) const;

WeightVector_exposer.def(
"SquaredNorm"
, SquaredNorm_function_type( &::gezi::WeightVector::SquaredNorm ) );

}
{ //::gezi::WeightVector::ToVector

typedef ::gezi::Vector ( ::gezi::WeightVector::*ToVector_function_type )(  ) ;

WeightVector_exposer.def(
"ToVector"
, ToVector_function_type( &::gezi::WeightVector::ToVector ) );

}
{ //::gezi::WeightVector::Value

typedef ::Float ( ::gezi::WeightVector::*Value_function_type )( int ) const;

WeightVector_exposer.def(
"Value"
, Value_function_type( &::gezi::WeightVector::Value )
, ( bp::arg("index") ) );

}
{ //::gezi::WeightVector::dot

typedef ::Float ( ::gezi::WeightVector::*dot_function_type )( ::gezi::Vector const & ) const;

WeightVector_exposer.def(
"dot"
, dot_function_type( &::gezi::WeightVector::dot )
, ( bp::arg("other") ) );

}
{ //::gezi::WeightVector::dot

typedef ::Float ( ::gezi::WeightVector::*dot_function_type )( ::gezi::Vector const &,::Float ) const;

WeightVector_exposer.def(
"dot"
, dot_function_type( &::gezi::WeightVector::dot )
, ( bp::arg("other"), bp::arg("scale") ) );

}
{ //::gezi::WeightVector::dotOnDifference

typedef ::Float ( ::gezi::WeightVector::*dotOnDifference_function_type )( ::gezi::Vector const &,::gezi::Vector const &,::Float ) const;

WeightVector_exposer.def(
"dotOnDifference"
, dotOnDifference_function_type( &::gezi::WeightVector::dotOnDifference )
, ( bp::arg("other1"), bp::arg("other2"), bp::arg("scale")=1.0e+0 ) );

}
{ //::gezi::WeightVector::operator[]

typedef ::Float ( ::gezi::WeightVector::*__getitem___function_type )( int ) const;

WeightVector_exposer.def(
"__getitem__"
, __getitem___function_type( &::gezi::WeightVector::operator[] )
, ( bp::arg("index") ) );

}
WeightVector_exposer.def_readwrite( "squaredNorm", &gezi::WeightVector::squaredNorm );
}

bp::class_< gezi::SparseWeightVector, bp::bases< gezi::WeightVector > >( "SparseWeightVector" )
.def(
"Add"
, (void ( ::gezi::SparseWeightVector::* )( ::gezi::Vector & ) )( &::gezi::SparseWeightVector::Add )
, ( bp::arg("a") ) )
.def(
"Add"
, (void ( ::gezi::SparseWeightVector::* )( ::gezi::SparseWeightVector & ) )( &::gezi::SparseWeightVector::Add )
, ( bp::arg("a") ) )
.def(
"AddScale"
, (void ( ::gezi::SparseWeightVector::* )( ::gezi::Vector &,::Float ) )( &::gezi::SparseWeightVector::AddScale )
, ( bp::arg("a"), bp::arg("scale") ) )
.def(
"AddScale"
, (void ( ::gezi::SparseWeightVector::* )( ::gezi::SparseWeightVector &,::Float ) )( &::gezi::SparseWeightVector::AddScale )
, ( bp::arg("a"), bp::arg("scale") ) );

bp::class_< gezi::TextPredictor >( "TextPredictor" )
.def(
"Prase"
, (void (*)( ::svec const &,::std::map< int, double > &,::gezi::DoubleIdentifer const &,int,int,int,::std::string ))( &::gezi::TextPredictor::Prase )
, ( bp::arg("words_"), bp::arg("m"), bp::arg("identifer"), bp::arg("startIndex")=(int)(0), bp::arg("ngram")=(int)(3), bp::arg("skip")=(int)(2), bp::arg("sep")="\001" ) )
.def(
"Predict"
, (double (*)( ::svec const &,::svec const &,::gezi::DoubleIdentifer const &,::gezi::PredictorPtr const &,int,int,int,::std::string ))( &::gezi::TextPredictor::Predict )
, ( bp::arg("titleWords"), bp::arg("contentWords"), bp::arg("identifer"), bp::arg("predictor"), bp::arg("segType")=(int)(gezi::SEG_BASIC), bp::arg("ngram")=(int)(3), bp::arg("skip")=(int)(2), bp::arg("sep")="\001" ) )
.def(
"Predict"
, (double (*)( ::svec const &,::gezi::DoubleIdentifer const &,::gezi::PredictorPtr const &,int,int,int,::std::string ))( &::gezi::TextPredictor::Predict )
, ( bp::arg("words"), bp::arg("identifer"), bp::arg("predictor"), bp::arg("segType")=(int)(gezi::SEG_BASIC), bp::arg("ngram")=(int)(3), bp::arg("skip")=(int)(2), bp::arg("sep")="\001" ) )
.def(
"Predict"
, (double (*)( ::std::string,::std::string,::gezi::DoubleIdentifer const &,::gezi::PredictorPtr const &,int,int,int,::std::string ))( &::gezi::TextPredictor::Predict )
, ( bp::arg("title"), bp::arg("content"), bp::arg("identifer"), bp::arg("predictor"), bp::arg("segType")=(int)(gezi::SEG_BASIC), bp::arg("ngram")=(int)(3), bp::arg("skip")=(int)(2), bp::arg("sep")="\001" ) )
.def(
"Predict"
, (double (*)( ::std::string,::gezi::DoubleIdentifer const &,::gezi::PredictorPtr const &,int,int,int,::std::string ))( &::gezi::TextPredictor::Predict )
, ( bp::arg("content"), bp::arg("identifer"), bp::arg("predictor"), bp::arg("segType")=(int)(gezi::SEG_BASIC), bp::arg("ngram")=(int)(3), bp::arg("skip")=(int)(2), bp::arg("sep")="\001" ) )
.staticmethod( "Prase" )
.staticmethod( "Predict" );

{ //::gezi::to_features

typedef ::gezi::Vector ( *to_features_function_type )( ::std::string );

bp::def(
"to_features"
, to_features_function_type( &::gezi::to_features )
, ( bp::arg("sparseFeatureStr") ) );

}

{ //::gezi::write_def

typedef void ( *write_def_function_type )( ::gezi::Features const &,::std::string );

bp::def(
"write_def"
, write_def_function_type( &::gezi::write_def )
, ( bp::arg("features"), bp::arg("outfile") ) );

}

{ //::gezi::write_header

typedef void ( *write_header_function_type )( ::gezi::Features const &,::std::string );

bp::def(
"write_header"
, write_header_function_type( &::gezi::write_header )
, ( bp::arg("features"), bp::arg("file") ) );

}

{ //::gezi::write_template

typedef void ( *write_template_function_type )( ::gezi::Features const &,::std::string );

bp::def(
"write_template"
, write_template_function_type( &::gezi::write_template )
, ( bp::arg("features"), bp::arg("outfile") ) );

}
}
